layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
     - test-repo
     - hello-react-code
     - colt-react-course
     - todo-list-OC

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: https://www.linkedin.com/in/ceheiss/
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: Cristobalheiss
  # unsplash: your_username
  # vk: your_username
  website: https://codepen.io/ceheiss/
  # youtube: your_username

topics:

  - name: Javascript
    web_url: https://developer.mozilla.org/en-US/docs/Web/JavaScript
    image_url: https://miro.medium.com/max/3600/1*6ahbWjp_g9hqhaTDSJOL1Q.png

  - name: React
    web_url: https://reactjs.org/
    image_url: http://blog.addthiscdn.com/wp-content/uploads/2014/11/addthis-react-flux-javascript-scaling.png

  - name: TDD
    web_url: https://www.freecodecamp.org/news/test-driven-development-what-it-is-and-what-it-is-not-41fa6bca02a2/

  - name: HTML5
    web_url: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5#targetText=HTML5%20is%20the%20latest%20evolution,powerful%20Web%20sites%20and%20applications.
    image_url: http://www.webdevelopmenthelp.net/wp-content/uploads/2015/09/HTML55.png

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
